package Model.Enumeration;

public enum TileName {
    CORAL_PALACE("CORALPALACE"),
    TIDAL_PALACE("TIDALPALACE"),
    WHISPERING_GARDEN("WHISPERINGGARDEN"),
    HOWLING_GARDEN("HOWLINGGARDEN"),
    TEMPLE_OF_THE_MOON("TEMPLEOFTHEMOON"),
    TEMPLE_OF_THE_SUN("TEMPLEOFTHESUN"),
    CAVE_OF_SHADOWS("CAVEOFSHADOWS"),
    CAVE_OF_EMBERS("CAVEOFEMBERS"),
    MISTY_MARSH("MISTYMARSH"),
    CRIMSON_FOREST("CRIMSONFOREST"),
    WATCHTOWER("WATCHTOWER"),
    OBSERVATORY("OBSERVATORY"),
    DUNES_OF_DECEPTION("DUNESOFDECEPTION"),
    COPPER_GATE("COPPERGATE"),
    BRONZE_GATE("BRONZEGATE"),
    IRON_GATE("IRONGATE"),
    SILVER_GATE("SILVERGATE"),
    GOLD_GATE("GOLDGATE"),
    PHANTOM_ROCK("PHANTOMROCK"),
    BREAKERS_BRIDGE("BREAKERSBRIDGE"),
    FOOLS_LANDING("FOOLSLANDING"),
    LOST_LAGOON("LOSTLAGOON"),
    TWILIGHT_HOLLOW("TWILIGHTHOLLOW"),
    CLIFFS_OF_ABANDON("CLIFFSOFABANDON");

    private final String displayName;

    TileName(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}